### ISSUE TITLE
Use Default namespace if defined

### ISSUE THREAD

**Issue by jbestrom** [pauer24/VsNamespaceFixer#1]
Is there a way to get this to use the default namespace of the project if it is defined rather than folder structure?

Example:
Solution->Project->Folder will produce Solution.Project.Folder
If I have (Project) set to use Default namespace of ServerFiles it would be nice if it would be ServerFiles.Folder

**Comment by GothicSecret** [comment]
+1

**Comment by pauer24** [comment]
Dear devs, I just uploaded this feature. If you feel it can be improved, feel free to comment.
The root of namespace now can be set from the csproj.

**Comment by spottedmahn** [comment]
Hi @pauer24 - can you link to the PR?

**Comment by spottedmahn** [comment]
I think I found the commit: 8d2edcb615d2991b1810ce938495561157ee931c
