### ISSUE TITLE
Spaces in file names cause compile errors

### ISSUE THREAD

**Issue by bjorndavis** [pauer24/VsNamespaceFixer#12]
If a filename has a space (e.g. "The File") it will retain that space in the namespace, which causes a compile error.  It might be more useful to replace that space with an underscore (e.g. "The_File").

**Comment by pauer24** [comment]
I don't get the error you are refering to. The file name has nothing to do with its namespace, is it? Could you please provide a complete use case?

**Comment by bjorndavis** [comment]
Apologies, I misspoke.  It does not happen with file names that have spaces, but rather folder names and project names.  I've added a few screenshots.
![namespace 1a](https://user-images.githubusercontent.com/4430868/54694098-ecf52b00-4ae4-11e9-9a38-69009bdadee8.PNG)
![namespace 2a](https://user-images.githubusercontent.com/4430868/54694100-ed8dc180-4ae4-11e9-926a-8b54d3939f66.PNG)
![namespace 1b](https://user-images.githubusercontent.com/4430868/54694101-ed8dc180-4ae4-11e9-8943-ed9ef7ff1e34.PNG)
![namespace 2b](https://user-images.githubusercontent.com/4430868/54694102-ed8dc180-4ae4-11e9-9179-6dbb2fdfb4f3.PNG)

**Comment by pauer24** [comment]
Hmmm I thought I already considered that case... I'll take a look and hope
to find time during this week. Thanks to raise the issue!

**Comment by pauer24** [comment]
It has been corrected and the new version uploaded. It should be available in a few hours...
