### ISSUE TITLE
Add a new section to namespace format {defaultNamespace}

### ISSUE THREAD

**Issue by lawrence-laz** [pauer24/VsNamespaceFixer#14]
Project properties contain a _default namespace_ property, which I would like to be able to use instead of a project's name when adjusting namespaces.

Reasoning behind this is that I like project names within solution to be short like "Business" and "Api", while namespaces have to contain a full name like "MyProject.Business" and "MyProject.Api".

**Comment by pauer24** [comment]
Hello, I'd say it's already considered. Have you seen the options it allows
you?

You can check on them on the extension site:
https://marketplace.visualstudio.com/items?itemName=p2410.NamespaceFixer

Hope it suits you.

Regards,

**Comment by lawrence-laz** [comment]
I don't know how I missed that, sorry!

This is exactly what I needed.
