### ISSUE TITLE
Section {projectRootNamespace} includes '.csproj' extension in namespace.

### ISSUE THREAD

**Issue by lawrence-laz** [pauer24/VsNamespaceFixer#15]
Hi,

I've noticed a problem with fixing namespaces inside .NET Standard and .NET Core projects. This does not reproduce in .NET Framework.

The problem is that after adjusting the namespace while using a `{projectRootNamespace}` section the namespaces include `.csproj`.

This is reproduced in Visual Studio 2017 (15.9.11).

**Comment by pauer24** [comment]
This issue has been addressed and solved. You'll find an update in a few hours :)

**Comment by lawrence-laz** [comment]
Great, thank you!
