### ISSUE TITLE
Original file encoding is not preserved

### ISSUE THREAD

**Issue by chvogel** [pauer24/VsNamespaceFixer#18]
Steps to reproduce:
- Have a code file encoded in UTF-8 with BOM ("UTF-8 with signature" / Codepage 65001) and contains a wrong namespace.
- Use "Adjust namespace" on that file.

Expected results:
- Namespace is fixed.
- File encoding is preserved.

Actual results:
- Namespace is fixed.
- File is stored in UTF-8 encoding.

Effect:
Since all our new code files are encoded in UTF-8 with BOM (set via .editorconfig policy), this behavior causes individual files to start becoming "contaminated" with a wrong encoding (if not adjusted manually), which may spread to other files if the contaminated file is copied for example.

**Comment by pauer24** [comment]
This issue has been addressed and solved. You'll find an update in a few hours :)
