### ISSUE TITLE
16.3.0 Preview 2 Broke the Extension?

### ISSUE THREAD

**Issue by spottedmahn** [pauer24/VsNamespaceFixer#22]
I think the latest version of VS 2019 Preview introduced a breaking change.  I use this tool on a daily basis and I've never seen this before.  Could be not related to the latest version of VS but that's not what my gut says.

After running the extension I end up with malformed code:

```
using MyProject.Core.Entities;

namespace MyProject.Domain.MyNewNamespace
{
using System;

namespace MyProject.Core.MyOldNamespace
{
...
}}
```

**Comment by pauer24** [comment]
Hmmm.. I think it was me and @Tr4ncer that introduced that bug... Let me take a look at it.

**Comment by Tr4ncer** [comment]
:scream: 

Can be a problem with regular expressions?

**Comment by pauer24** [comment]
Yep, the change that I introduced 💪. Apparently I didn't test it deep enought... 😅 On my way to solve it!

**Comment by Tr4ncer** [comment]
:grin: It's the live, anything can happen!

If you need help, do not hesitate.

**Comment by spottedmahn** [comment]
>On my way to solve it!

Thanks @pauer24! 🤝

**Comment by spottedmahn** [comment]
oh, I see, I'm on auto-update.  So when I update VS it closed VS did it upgrade and then upgrade this extension.

![image](https://user-images.githubusercontent.com/14079228/63039643-bf44c000-be91-11e9-9271-e8c42bf434f1.png)

**Comment by pauer24** [comment]
No worries, the fix is already uploaded. I guess in few hours will be published. Feel free to assert tomorrow it's working as expected :) @Tr4ncer, I left the Regex as you wrote them. I tried to ensure it's at the beginning of the line, so if a using is in an string, it's not the last found, but my Regex are more rusty than expected. Someday I'll fix it 😜

**Comment by spottedmahn** [comment]
Thanks!  I'll veryify "tomorrow".

For reference, can you share the PR link?
