### ISSUE TITLE
Namespace Fixer adds namespace declarations to CSHTML files

### ISSUE THREAD

**Issue by AnLoffredo** [pauer24/VsNamespaceFixer#27]

**Comment by pauer24** [comment]
You can add cshtml in the extensions to exclude in the Options section

**Comment by AnLoffredo** [comment]
Will do. Might be a good idea to exclude it by default though, since I'm not aware of a situation where it would be desired. Its like namespacing an HTML file

**Comment by pauer24** [comment]
Feel free to do it yourself :) Not that it's a difficult task, but this
way, you can start seeing the code and implementing your own features ;)

Cheers!
