### ISSUE TITLE
Breaks Json files.

### ISSUE THREAD

**Issue by TopSwagCode** [pauer24/VsNamespaceFixer#28]
Thank you for the awesome tool :) When I ran it, it was a bit to effective ;) It tried to apply namespaces to my Json files in the project. Perhaps it should have some ignore logic ?

```json
    namespace SomethingAwesome.test.LogicTest
    {
    {
      "status": "success",
      "data": { 
    ........
```

**Comment by pauer24** [comment]
Already implemented! :) If you go to the options section you will find it
there.
I won't do the change myself and by default because I prefer that you do
it, so in the future if you want to implement extra functionalities you
will have a bit of knowledge already.

Cheers!!
