### ISSUE TITLE
Use Default-Namespace instead of project name

### ISSUE THREAD

**Issue by angelobreuer** [pauer24/VsNamespaceFixer#30]
Hello,

I have the problem that I have multiple projects which have a different default namespace (specified in project file). I would like that the default namespace is used instead of the project name.

![Problem Description](https://user-images.githubusercontent.com/46497296/68076693-5a29a800-fdb8-11e9-999a-65ed6c8c1b2a.png)

I am using the latest version of the extension (Version 2.5) with Microsoft Visual Studio 2019 Community Preview (Version 16.4.0 Preview 1.0).

Thanks in advance.

**Comment by angelobreuer** [comment]
Sorry, invalid issue. 
There's already a solution (Tools > Options > Namespace fixer options).

![image](https://user-images.githubusercontent.com/46497296/68076753-39ae1d80-fdb9-11e9-9cdd-58694d1ad605.png)


Is there any reason why the project name is the default setting?

**Comment by pauer24** [comment]
Well, since it's the first complain over 10k downloads, I guess it's ok
this way.
