### ISSUE TITLE
Error when the solution file is not in the same directory as the project(s)

### ISSUE THREAD

**Issue by angelobreuer** [pauer24/VsNamespaceFixer#31]
I have the problem, that my project structure is as the following:

```ascii-art
<root>/
├── src/
│     ├── Project1/
│     ├── Project2/
│     └── Solution.sln
└── extensions/
      ├── Extension1/
      └── Extension2/
```

When I try to Fix Namespaces in Project1 or Project2 it works as expected, but if I try to fix namespaces in Extension1 or Extension2, the following error appears:

![Error Message](https://user-images.githubusercontent.com/46497296/69918375-6d8c6980-1471-11ea-9733-f16237ca1011.png)

The projects Extension1 and Extension2 are all in the same solution as Project1 and Project2.

The problem is that the extension can not find the solution file because it is not in the same directory as the projects.

Thanks in advance.

**Comment by pauer24** [comment]
It's been solved thanks to you! I've already add an special thank to your stunning job. Welcome to the team!
