### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by aquilla12** [pauer24/VsNamespaceFixer#33]
In [this blogpost](https://devblogs.microsoft.com/visualstudio/getting-started-writing-visual-studio-extensions/) Mads Kristensen suggests using open source extensions to learn how to write your own VS extensions.

> ### Use open source as a learning tool
> 
> You probably have ideas about what you want your extension to do and how it should work. But what APIs should you use and how do you hook it all up correctly? These are difficult questions and a lot of people give up when these go unanswered.
> 
> The best way I know of is to find extensions on the Marketplace that does similar things or uses similar elements as to what you want to do. Then find the source code for that extension and look at what they did and what APIs they used and go from there.

Following his advice, I was very grateful to be able to use part of your code in developing an extension of my own, as it demonstrated exactly what I wanted to do. However I have just realized that you have not provided a license for your code.

Please consider providing a license, as this helps others who may want to build on your work or reuse some of it,.

**Comment by pauer24** [comment]
Thanks! Already done it.
Cheers!

**Comment by aquilla12** [comment]
Thank you 😄

**Comment by aquilla12** [comment]
Sorry to be back, but I'm having concerns around [githubs's advice on the legal side of open source](opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project).

This article says that to add a license to unlicensed project, all contributors must agree to release their contributions to the new terms. 

> But if your current license is not permissive (e.g., copyleft, or you don’t have a license) and you aren’t the sole copyright holder, you couldn’t just change your project’s license to MIT.
> ...
>If you’re the sole contributor to your project then either you or your company is the project’s sole copyright holder. You can add or change to whatever license you or your company wants to. Otherwise there may be other copyright holders that you need agreement from in order to change licenses.

I would like to confirm for my protection, and yours, that this has been done.

**Comment by pauer24** [comment]
Hey guys, as @aquilla12 noticed, I added a licence, and this requires the aknowledge and premission of all the contributors, so I'm asking around here: is it OK for you that I added the MIT licence? @Tr4ncer , @spottedmahn , @DawidB , @angelobreuer .

If you have said nothing in a week, I will interpret it as an OK.

**Comment by DawidB** [comment]
Hi @pauer24. MIT license is fine with me :).

**Comment by blankensteiner** [comment]
Just a note, legally that's not how it works, you can't just interpret that as an "Ok", we need a confirmation.

**Comment by pauer24** [comment]
So if I don't get an answer for just one of the people that collaborate with the code I can't put any licence on it?

**Comment by blankensteiner** [comment]
Let's see if it goes that way. If it does, then I have a friend I can ask who's a lawyer and working with IP.

**Comment by angelobreuer** [comment]
Sure! Thanks for asking. :)

**Comment by Tr4ncer** [comment]
Hello,

No problem for me.
Thanks for asking.

Take care of yourself.

**Comment by spottedmahn** [comment]
Hi @pauer24 👋 - MIT license is fine with me 👍

**Comment by aquilla12** [comment]
@pauer24 Many thanks for all your help!!
If you'd like to see what I've done, have look at https://github.com/aquilla12/ExtensibleBatchRunner
