### ISSUE TITLE
[Bug] Does not fix Xaml namespace.

### ISSUE THREAD

**Issue by koddek** [pauer24/VsNamespaceFixer#34]
Hi, thanks for this great addon.
## Problem
In a Xamarin Forms app, when I select a folder with XAML and cs files and use the Fix Namespace feature, it correctly fixes the namespaces for .cs files but not for .xaml files. Furthermore, it surrounds all the XAML content in the cs namespace causing errors.

Basically it breaks XAML files.

## Expected Behavior
I expect the addon to update the namespace of all files within the folder, both .cs, and XAML. And it would be nice to confirm that the task was completed.

**Comment by pauer24** [comment]
Hello koddek! You are not the first one to notice this, and I always give the same answer:
- You can ignore those xaml file from add the namespace in the Extension Configuration page, inside the Options panels from VS
- If it's a feature that would make your work sooo much easy, you can add it yourself :) The code is pretty neat, and others have collaborated to improve it. Feel free to join the team 💪

**Comment by koddek** [comment]
@pauer24 thanks for the reply. I took a quick look at the project already, but it's over my head, that's why I requested the fix. One day I will be good enough but not there right now. :) I will try your recommendation.

**Comment by pauer24** [comment]
It's being discussed in the PR. Please be patient, I'm confident this week we'll have an stable and working version for XAML files. 
BTW, is C# that you are using, or VB?
Cheers!

**Comment by dust999** [comment]
@pauer24 can you explain how to recompile plugin on my side to make some chages inside it and tes it in visual studio? I'm not a pro in c# but have a few ideas how to fix broken links

**Comment by pauer24** [comment]
Sure thing! It's so simple. Just install the module of development
extensions,when modifying the installation of VS itself.

Then just open the solution, and run! It will open a sandbox of VS with the
developed extension installed.

Thanks and good luck!

P.

**Comment by dust999** [comment]
Thanks, I'll try.
