### ISSUE TITLE
Default namespace renaming does not follow the VS rules

### ISSUE THREAD

**Issue by ygavrishov** [pauer24/VsNamespaceFixer#36]
When I create a new C# class, it is created in default project namespace. Otherwise, when I use the "Adjust Namespace" feature, it changes namespace using the _{projectName}{fileToProjectPath}_ template.

I would suggest using _{projectRootNamespace}{fileToProjectPath}_ template by default.

P.S. I know that it's possible to change the template in the extension settings.

**Comment by pauer24** [comment]
Definitely is a good suggestion, I have already considered and as soon as we have new functionality to release, I will add this one.

Cheers!

**Comment by pauer24** [comment]
Hello! The defaults have been updated in this new version. Thanks a lot for
your comments.

Cheers!

**Comment by pauer24** [comment]
It's been solved in the current version
