### ISSUE TITLE
[Bug] Destroys winform resx files

### ISSUE THREAD

**Issue by yarecky1** [pauer24/VsNamespaceFixer#37]
After applying fix on folder where `System.Windows.Forms` exist, this extension adds namespace to all resx files attached to `form` files. This generates many compilation errors and forces to manually repair all resx files outside VS using notepad because resx file stops being recognizable by VS.

Before:
```
<?xml version="1.0" encoding="utf-8"?>
<root>
...
</root>
```
After:
```
Namespace #######
<?xml version="1.0" encoding="utf-8"?>
<root>
...
</root>
End Namespace
```

Please fix it ASAP because currently extension is useless on feature folders (form file with all other files - services, helper and other classes).

**Comment by pauer24** [comment]
Hello!

You can find and exclude file by extension options on the options sections
of the extension.
Anyway, I will add by default the .resx extension to the excluded
extensions.

Cheers!

**Comment by yarecky1** [comment]
Hi,

True. I found this option 5 minutes after I posted the issue. But i decided to keep open because as you noticed it should be excluded by default.

Thank you ;)

**Comment by pauer24** [comment]
Hello! The default options have been changed.
Cheers!

**Comment by yarecky1** [comment]
Cool. Thanks! I close the issue.
