### ISSUE TITLE
[Bug] 'Unsupported file extension' exception

### ISSUE THREAD

**Issue by azelion** [pauer24/VsNamespaceFixer#38]
The CreateNamespaceBuilderService method in NamespaceBuilderFactory throws an exception for files that it cannot fix the namespace for (e.g. .jpg/.png) but the ignored extensions aren't used until FixNamespace does a check to IgnoreFile(string filePath)

I think the CreateNamespaceBuilderService should return a default c# builder instead of throwing an exception or the ignored file list should be used there.

**Comment by pauer24** [comment]
Hello! It has been updated, and it won't trigger the error anymore :)

**Comment by azelion** [comment]
Nice! Works as expected. Thanks for your work!
