### ISSUE TITLE
Add 'use root namespace in all subdirs' option

### ISSUE THREAD

**Issue by GothicSecret** [pauer24/VsNamespaceFixer#4]
Can you please add this option to make it set the root namespace within the whole project, regardless of subfolders.
IE: ProjFolderName = "MyProj"
subfolders: sub1, sub2.
files in subfolders should have: "MyProj" bnamespace.

**Comment by pauer24** [comment]
There is this option already :) 
You will find it on: Options > Namespace Fixer options.

Cheers!

**Comment by GothicSecret** [comment]
you didn't got the main idea...
I talked about SUB-folders in the Proj folder.
Like ProjFolder1 contains 2 subfolders: sub1, sub2.
and NOW files in these subfolders have namespace ProjFolder1.sub1, ProjFolder1.sub2
BUT I want they have ProjFolder1 and ProjFolder1. So ALL the files in the project have the SAME namespace.

**Comment by GothicSecret** [comment]
I can show you how I done it. in the copy of your code. I add new menu item. and make it work as I want.
https://github.com/GothicSecret/NamespaceFixerWithRootFolder/blob/e61a9d1a595a9ef6f885d5034fb3bb74de10d422/NamespaceFixer/NamespaceBuilder/NamespaceBuilderService.cs
the method name is: GetIdealNamespace2

**Comment by pauer24** [comment]
Ah, right, I thought it was already done... I will take a look at it, it won't be any difficult. In fact, if you are in a rush for this functionality, you can fork and then do a pull request :)

Cheers!

**Comment by GothicSecret** [comment]
Not critical for me)
I already had done it with prev version.
I add new menu item, I think it's better than just option. Because it
allows you to make some directories independent of other.

чт, 3 мая 2018 г., 09:55 pauer24 <notifications@github.com>:

**Comment by pauer24** [comment]
Right. I will take this consideration 👍
