### ISSUE TITLE
VS2022

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [pauer24/VsNamespaceFixer#43]
Any plans to support Visual Studio 2022? 🙂  Asking for one of my coworkers who uses this extension.

**Comment by pauer24** [comment]
Well it's planned in my mind, but I don't have specific date in mind.

But feel free to update it yourself or your coworker; at the end is open
source! :D

Regards,

P.

**Comment by Bosch-Eli-Black** [comment]
@pauer24 Haha, okay, thanks! 🙂  I'll let my coworker know :)  Our company requires us to take a class before contributing to open source projects. Maybe he's taken it, but I doubt it, haha. No pressure, and thanks for the reply 🙂

Do you mind if I leave this open, so that others can see the migration status? 🙂

**Comment by pauer24** [comment]
It seems a pretty good idea for me to keep it open :)

**Comment by Bosch-Eli-Black** [comment]
Sounds good! 🙂

**Comment by pauer24** [comment]
Hi, it seems the extension for 2019 has been already migrated somehow and it's valid in VS2022 :)

I'm already using it. Therefore I'm closing this issue .

Cheers!

**Comment by Bosch-Eli-Black** [comment]
Oh, cool!

Thanks! 🙂

**Comment by dgunderson** [comment]
> Hi, it seems the extension for 2019 has been already migrated somehow and it's valid in VS2022 :)
> 
> I'm already using it. Therefore I'm closing this issue .
> 
> Cheers!

Hi! I used this extension _all the time_ in VS2019 and there's just nothing as good/simple in 2022. When I try to install it, I get this message:

![image](https://user-images.githubusercontent.com/5771312/167186275-e04949e0-0d2b-4153-bf86-49ce7a8b431c.png)

If it does indeed work in 2022, what am I doing wrong?

Thanks!

**Comment by dgunderson** [comment]
I just noticed the Q&A on the marketplace listing [here](https://marketplace.visualstudio.com/items?itemName=p2410.NamespaceFixer&ssr=false#qna). Looks like it's indeed not able to be installed on VS 2022, not sure how you are able to use it. Luck you!

**Comment by pauer24** [comment]
Indeed... It seems that a previous feature allowed the option (I have an
instance of VS2022 with the extension running as I said before...) of
installing it but for some reason it's not working anymore...

Feel free to update it yourself, or kindly wait until I need it so bad that
I have to migrate it myself 😖

Regards!
