### ISSUE TITLE
Could not find project file on project directory

### ISSUE THREAD

**Issue by spottedmahn** [pauer24/VsNamespaceFixer#5]
I changed my setting to use the project namespace as I don't want the root folder in my namespaces but when I run the extension I get:

![image](https://user-images.githubusercontent.com/14079228/42944781-964b0c68-8b34-11e8-9f37-df7cb4a13c0a.png)

---

![image](https://user-images.githubusercontent.com/14079228/42944736-775036e4-8b34-11e8-880d-8a6df8de5f36.png)

![image](https://user-images.githubusercontent.com/14079228/42944768-8dec96d6-8b34-11e8-9eb6-840753b9220d.png)

**Comment by pauer24** [comment]
Thanks for reporting the bug!

To be able to reproduce it, I'd need to know if you performed some renaming
on the solution, the projects, or the projects internal path. Some of these
cases may not be fully covered by the plugin, so if you can help me out
with this I will fix it in a second.

**Comment by spottedmahn** [comment]
>To be able to reproduce it

Hi @pauer24 - happy to provide whatever info to track this down.

>I'd need to know if you performed some renaming
on the solution, the projects, or the projects internal path.

Could have, not really sure what steps I've performed.

-----

Does your extension perform any logging?  Can extension "log" to the Output window?

**Comment by pauer24** [comment]
This bug has been fixed. The current version is being reviewed, and in a hurry you should be able to update it and keep working!

**Comment by spottedmahn** [comment]
nice, thanks @pauer24! 💪
