### ISSUE TITLE
Adjust namespace in windows form

### ISSUE THREAD

**Issue by konytskyy** [pauer24/VsNamespaceFixer#6]
If you adjust namespace for windows form - for example:

frmEdit.cs 
frmEdit.Designer.cs

if you select  frmEdit.cs - namespace is changed for  for frmEdit.cs but NOT for frmEdit.Designer.cs. 
You have to select frmEdit.Designer.cs to change its namespace which is not what expected.

**Comment by pauer24** [comment]
Ooops! Such an issue! Going to fix it right now!

Thanks for the report

**Comment by pauer24** [comment]
This feature has been added. The current version is being reviewed, and in a hurry you should be able to update it and keep working!
