### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by spottedmahn** [pauer24/VsNamespaceFixer#7]
I'm receiving the following exception:

![image](https://user-images.githubusercontent.com/14079228/43902963-54b2b5a4-9bb9-11e8-824b-0622771f0c4a.png)

### Version
![image](https://user-images.githubusercontent.com/14079228/43902980-60c6cce0-9bb9-11e8-9127-15202ee99e1f.png)

---

What additional info I can I provide to track this down?  Thanks 🙏

**Comment by spottedmahn** [comment]
Hi @pauer24 - please see this SLN structure:

![image](https://user-images.githubusercontent.com/14079228/43961646-8fae1700-9c83-11e8-8c0a-35da0e1c0e54.png)

Does that help track it down?

**Comment by spottedmahn** [comment]
Does your extension write the Output window?  Might be handy if it doesn't as a way of logging.

**Comment by spottedmahn** [comment]
> Could it be that your solution has 2 .sln or .csproj files in the same directory? If that is the case, could you explain me why you need it this way?

Yes there is.  To provide a better level of organization 😊

![image](https://user-images.githubusercontent.com/14079228/43967664-e967b094-9c92-11e8-8f63-4bb31ec361de.png)

![image](https://user-images.githubusercontent.com/14079228/43967712-0c4a78da-9c93-11e8-98a8-e01d98e4c7e7.png)

**Comment by pauer24** [comment]
As far as I can see you have multiple projects inside a logical folder of the solution, and that's fine, as long as each project have it's own physical folder. Is that your case? Does every project have it's physical folder with the .csproj file inside?

**Comment by spottedmahn** [comment]
Hi @pauer24 - they are actual physical folders...

![image](https://user-images.githubusercontent.com/14079228/44095626-4cfca440-9fa7-11e8-985f-f04448ac619a.png)

![image](https://user-images.githubusercontent.com/14079228/44095663-61b52f9c-9fa7-11e8-9ec7-a9ae81ffb844.png)

**Comment by pauer24** [comment]
Then I don't get it... The only explanation for this error is that there are multiple *.sln or *.csproj files on the same physical folder. Is there any chance this is your situation?

**Comment by spottedmahn** [comment]
Hi @pauer24 - yes, [that is the case](https://github.com/pauer24/VsNamespaceFixer/issues/7#issuecomment-412878174).

**Comment by pauer24** [comment]
And witch of both cases is yours? I hope is 2 .sln files on the same folder because on .NET Core the files are not specified on the .csproj, it just includes all bellow it (and if you plan to migrate at some point you might have issues).
If it's the 2 .sln files I could tweak it to look for the solution if it's not specified on the plug-in options.

**Comment by spottedmahn** [comment]
>The only explanation for this error is that there are multiple *.sln or *.csproj files on the same physical folder. 

Sorry, just re-read this... yes, there are **two** `*.sln` files in same folder.

![image](https://user-images.githubusercontent.com/14079228/44413564-ab45d700-a539-11e8-92ce-6a1345c490ee.png)

**Comment by pauer24** [comment]
It's been solved finally! Now it's working even if you have 2 sln files. Just be aware if you want to use the {solutionName} flag will take the first one

**Comment by spottedmahn** [comment]
Hi @pauer24 - thanks!

I would have thought it would only be concerned w/ the SLN that is open, no?
