### ISSUE TITLE
Release extension to VS2019 Enterprise Preview

### ISSUE THREAD

**Issue by mniak** [pauer24/VsNamespaceFixer#9]
This extension is sooo useful 😄!
I stopped using VS2019 Enterprise Preview because some extensions were not released to it.

**Comment by pauer24** [comment]
Didn't even consider that! I'll take a look on how to migrate some time...
Thanks for the comment btw, it helps to keep going 💪

**Comment by mniak** [comment]
I've done that.
Please accept it so I can download from the store.
I'm currently using the version I build my own.

**Comment by spottedmahn** [comment]
Hi @pauer24 - I love this extension!  Saves me so much time 👍

Any update on @mniak PR?  Thanks 😊

**Comment by pauer24** [comment]
Thanks to @spottedmahn comment I put myself again with this. 
Thanks to @mniak I saw tons of things I were doing wrong.

Now it's already published and pending of approval :D

**Comment by spottedmahn** [comment]
that's great, thanks @pauer24 👏

**Comment by spottedmahn** [comment]
I can now install on VS 2019!

![image](https://user-images.githubusercontent.com/14079228/54685208-a1467f80-4aec-11e9-89d2-ea4d2dd699af.png)

**Comment by pauer24** [comment]
You are all welcome. You are awesome :D
